from typing import List,Tuple

def test() -> None: ...
def add_i64(x: int, y: int) -> int: ...
def panic(msg: str) -> None: ...
def sort_tuple_str_int(arr: List[Tuple[str, int]]) -> List[Tuple[str, int]]:...
def reverse_sort_tuple_str_int(arr: List[Tuple[str, int]]) -> List[Tuple[str, int]]:...
